Resources
1. Basics
i. HTML: First pillar & the most important skill for web developers as it provides the structure for a web page.
•	Learn the basics of HTML
•	Make a few pages as an exercise
You can check Tutorial For HTML.
ii. CSS
•	Learn the basics of CSS
•	Style pages from the previous step
•	Build a page with grid and flexbox
You can check Tutorial For CSS.
iii. JS Basics
•	Get familiar with the syntax
•	Learn basic operations on DOM
•	Learn mechanisms typical for JS (Hoisting, Event Bubbling, Prototyping)
•	Make some AJAX (XHR) calls
•	Learn new features (ECMA Script 6+)
•	Additionally, get familiar with the jQuery library
You can check tutorials for JavaScript
2. General Development Skills:
The following are some skills you will require as by learning these skills you’ll be able to start your journey as a Vuejs developer with ease. It is one of the vital parts of this roadmap for Vuejs developers, as these skills are highly essential.
•	Learn GIT, create a few repositories on GitHub, and share your code with other people
•	Don’t be afraid of using Google, Power Searching with Google
•	Know HTTP(S) protocol, and request methods (GET, POST, PUT, PATCH, DELETE, OPTIONS)
•	Get familiar with the terminal, and configure your shell (bash, zsh, fish)
•	Read a few books about design patterns
•	Read a few books about algorithms and data structures
•	Git and version control
Git is the tool used to save code and create different versions, allowing you to collaborate with other developers. The top place to store code and collaborate on open-source software is GitHub.
•	Learn Git from GitHub
•	Ranked Git tutorials
•	Git Complete: The definitive, step-by-step guide to Git
3. Learn Vue on the official website or complete some courses
Learning is the main aspect of any field. So, the more you learn more you gain knowledge. There are many courses available that can help you start with Vue Js. Do take help from the courses and articles.
4. Get familiar with the helpful tools that can help you:
It is necessary to invest some time in learning tools that you are going to use as a Vuejs developer like built tools, unit testing tools, debugging tools, etc.
As users are going to interact with your websites through a web browser, it is required to render your site in a proper way. So, it’ll be great to know about the tools that can help you to develop a satisfying app/website/product.
These tools allow you to test and fine-tune your pages in the browser itself, in ways specific to how the browser is interpreting your code.
Here are some of the useful tools:
i. Package Managers:
A package manager or package management system is a collection of software tools that automates the process of installing, upgrading, configuring, and removing computer programs for a computer’s operating system in a consistent manner.
It deals with packages, data in archive files, and distributions of software. Packages contain metadata, such as the software’s name, description of its purpose, vendor, version number, checksum (preferably a cryptographic hash function), and a list of dependencies necessary for the software to run properly.
Following are some useful Package managers
•	npm
•	yarn
•	pnpm
ii. Task Runners:
Task runners offer value through the automation of numerous development tasks such as compiling code, concatenating files, and spinning up development servers.
•	npm scripts
•	gulp
iii. Vue-CLI: Standard Tooling for Vue.js Development.
Vue provides an official CLI for scaffolding ambitious Single Page Applications quickly. It also provides batteries-included build setups for a modern front-end workflow. Besides, it takes only a few minutes to get up and running with hot-reload, lint-on-save, and production-ready builds.
iv. Webpack: A bundler for javascript and friends.
Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand. Through “loaders”, modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, and your custom stuff.
You can check the beginner’s guide to webpack.
v. Parcel: Blazing fast, zero-configuration web application bundler
The parcel has out-of-the-box support for JS, CSS, HTML, file assets, and more — no plugins needed. Besides, it prints syntax highlighted code frames when it encounters errors to help you pinpoint the problem.
vi. Storybook: Build bulletproof UI components faster
A storybook is an open-source tool for developing UI components in isolation to React, Vue, Angular, and more. It makes building stunning UIs organized and efficient.
5. Styling
i. CSS Preprocessor
A CSS preprocessor is a program that lets you generate CSS from the preprocessor’s own unique syntax. preprocessors can make CSS code more organized.
•	Sass/CSS
•	PostCSS
•	Less
•	Stylus
ii. Component libraries
A UI component library is a (usually) robust set of ready-made UI components such as buttons, inputs, dialogs, and so on. They serve as building blocks for layouts. Thanks to their modular nature, we can arrange components in many different ways to achieve unique effects
•	Quasar
•	Vuetify
•	iView
•	Vuesax
•	Bootstrap-Vue
6. State Management Pattern
It is a self-contained app with the following parts:
•	The state, the source of truth that drives our app;
•	The view, a declarative mapping of the state;
•	The actions, the possible ways the state could change in reaction to user inputs from the view.
i. Data persistence * vue-persistedstate
ii. Vuex
7. Routing
Routing is the process of selecting a path for traffic in a network or between or across multiple networks. Broadly, routing is performed in many types of networks, including circuit-switched networks, such as the public switched telephone network (PSTN), and computer networks, such as the Internet.
You can check the installation guide for Routing on the official Vue Site
Following are some useful tools
•	Vue Router
•	Router5
•	Vue-component-router
8. API Clients
An API client is a set of tools and protocols that operate from an application on a computer. They help you to bypass some operations when developing a web application rather than reinventing the wheel every time.
i. GraphQL
•	Apollo
•	Relay
ii. REST
•	Fetch
•	Axios
•	SuperAgent
9. Utility Libraries
The OpenGL Utility Library (GLU) is a computer graphics library for OpenGL. It consists of a number of functions that use the base OpenGL library to provide higher-level drawing routines from the more primitive routines that OpenGL provides. It is usually distributed with the base OpenGL package.
•	Lodash
•	Day.js
•	Ramda
•	Moment
•	Numeral
•	RxJS
10. Testing
Testing is a technique in which Graphical User Interface (GUI), functionality, and usability of web applications or software are tested. The goal of testing is checking overall functionalities to ensure the presentation layer of web applications or software is defect-free with successive updates. It is a vital skill for any Developer.
i. Unit Testing
Unit testing generally refers to the process of performing, either manually or in an automated way, a set of tests on a single “unit” of code.
It mainly consists of testing isolated parts of the code, as units. These units usually take the form of methods, properties, UI element actions, etc. It is the fastest and cheapest to apply.
•	Jest
•	vue-test-utils
•	Sinon
•	Mocha
•	Chai
•	AVA
•	Tape
ii. End to End Testing
In E2E testing, the developer tests the whole application together and test it as a user would do.
Basically, here developer tests the application’s workflow from beginning to end. The aim is to replicate real user scenarios so that the system can be validated for integration and data integrity.
The following are some helpful tools:
•	Nightwatch
•	Selenium, Webdriver
•	Puppeteer
•	Cucumber.js
You can check this detailed guide on End to End Testing.
iii. Integration Testing
Integration tests make sure that various parts of the app work together. It is one of the crucial and most important tests.
•	Karma
11. Internationalization
Internalization is the process of planning and implementing products and services so that they can be easily adapted for, users from any culture, region, or language.
Basically, you make your product, app, website, etc. acceptable for different regions and languages. It helps to grow your business as well.
•	vue-i18n: Vue I18n is an internationalization plugin of Vue.js. It easily integrates some localization features into your Vue.js application.
A Bootstrap Admin Dashboard at ThemeSelection are always Internationalization/i18n Ready
12. Server-Side Rendering
Server-side rendering (SSR), is the ability of an application to contribute by displaying the web page on the server instead of rendering it in the browser. The Server-side sends a fully rendered page to the client; the client’s JavaScript bundle takes over and allows the SPA framework to operate.
•	Nuxt
13. Static Site Generator
A static site generator is a publishing tool, which is essentially a set of tools for building static websites based on a set of input files. They apply data and content to templates and generate a view of a page that can be served to the visitors of a site.
•	VuePress
•	Gridsome
Here is a detailed article on What is a static site generator and which are they?. Also, you can have a look at Static site generators for Vue.
14. Mobile
Mobile apps are a necessity nowadays for any business. The following are some helpful frameworks that can help develop apps for mobile.
•	Quasar
•	Vue Native
•	Nativescript Vue
•	Weex
For more detail check this amazing article on Ultimate guide to mobile app development.
15. Desktop
No matter how mobiles get handy or compact, desktops are still in demand and as many people still prefer to browse on a big screen; desktop apps are important as well.
•	Quasar
•	Electron
•	NW.js
•	Vuido
You can check this helpful article on Desktop apps for front end development.
16. Keep Learning
So, after going through this guide, you can kickstart your journey as a Vue js developer for sure. Although, learning is the only key to success. For that, you have to practice and learn consistently.
Following are some helpful courses and articles:
•	VueJS tutorial
•	What is vuejs
•	Vue The complete Guide
•	Learn Vue Js

